# -*- coding: utf-8 -*-
"""kuggle_week01_homework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDjBgl81KNVoJtojv3x7mmGkAZ2I-GyY

#1.판다스 시작하기
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('drive/MyDrive/gapminder.tsv',sep='\t')

print(df)
print(df.head()) #1~6행 출력

#1.데이터프레임의 자료형 확인
print(type(df))
#shape-> 데이터 프레임이 가지고 있는 데이터의 행과 열의 크기에 대한 정보 출력
print(df.shape)
#해당 데이터가 어떤 열로 구성되어있는지 확인
print(df.columns)
#각 열의 자료 타입에 대한 정보 출력
print(df.dtypes)
print(df.info()) #info를 이용하는 것이 좀 더 자세함

#2.열단위 데이터 추출하기
country_df=df['country'] #하나의 열 출력
print(country_df.head())
subset=df[['country','continent','year']]
print(subset.head())

#3.행단위 데이터 추출하기
#loc는 인덱스 번호를 기준으로 출력
#iloc는 행 번호를 기준으로 출력
print(df.head())
#인덱스 번호는 0부터 시작, 행 데이터가 추가, 삭제되면 언제든지 변할 수 있음
print(df.loc[0]) #데이터셋의 첫번째 행 출력
print(df.loc[1703]) #데이터셋의 마지막 행 출력
print(df.tail(n=-1)) #tail()을 이용해서 마지막 행 출력
print(df.loc[[0,99,999]]) #여러가지 행을 한번에 출력
print(df.iloc[1]) #데이터셋의 첫번째 행 출력
print(df.iloc[-1]) #데이터셋의 마지막 행 출력

"""tail과 loc가 반환하는 자료의 차이점
* tail: 데이터 자료형=데이터 프레임

* loc: 데이터 자료형=시리즈
"""

#loc, iloc 사용 응용- 추출할 데이터의 행과 열을 지정하는 방법
#슬라이싱 구문 이용
subset=df.loc[:, ['year','pop']] #year, pop열의 모든 행 출력
print(subset.head())
subset2=df.iloc[:, [2,4]]
print(subset2.head())
#데이터 타입에 지정해야함
#loc는  문자형
#iloc는 정수형
#range 구문 이용
#지정하고 싶은 행이나 열 범위를 range로 묶고 리스트로 지정- 범위값 생성
small_range=list(range(5)) #전체범위는 5지만
print(small_range) #시작은 0부터라  5-1인 4행까지 출력
subset3=df.iloc[:,small_range]
print(subset3.head())
small_range2=list(range(3,6))
print(small_range2)
subset4=df.iloc[:,small_range2]
print(subset4.head())

#4. 기초적인 통계 계산하기
print(df.head(n=10))
#기대수명 열을 연도별로 그룹화하여 평균 계산하기
#step1. year로 group by 진행
#step2. lifeExp열 지정후 mean 이용
print(df.groupby('year')['lifeExp'].mean())
mean_lifeExp_by_year=df.groupby('year')['lifeExp'].mean()
print(mean_lifeExp_by_year)
print(df.groupby(['year','continent'])[['lifeExp','gdpPercap']].mean()) #복잡한 그룹연산
#그룹화한 데이터의 개수가 몇 개인지 알아보기
print(df.groupby('continent')['country'].nunique())#대륙별로 나라가 몇개인지

#5.그래프 그리기
import matplotlib.pyplot as plt
data=df.groupby('year')['lifeExp'].mean()
print(data)
data.plot()

"""#2. 판다스 데이터프레임과 시리즈"""

import pandas as pd

#1. 나만의 데이터 만들기
s=pd.Series(['banana',42]) #시리즈
print(s)
#데이터 프레임 생성 인덱스 명 지정 가능
scientists=pd.DataFrame(
    {
     'Occupation':['Chemist','Statistician'],
     'Born':['1920-07-25','1876-06-13'],
     'Died':['1958-04-16','1937-10-16'],
     'Age':[37,61]},
    index=['Rosaline Franklin','William Gosset'],
    columns=['Occupation','Born','Died','Age'])
print(scientists)

#2. 시리즈 다루기-기초
#데이터 프레임에서 시리즈를 선택하려면 loc 속성에 인덱스를 전달
#정말 시리즈를 선택한 것인지 확인하기 위해 type으로 한번 더 검사
first_row=scientists.loc['William Gosset']
print(first_row)
print(type(first_row)) #시리즈를 선택한 것인지 확인하기 위한 검사

"""

*   index: 시리즈의 인덱스가 들어있음 (속성)
*   values: 시리즈의 데이터가 들어있음

"""

print(first_row.index)
print(first_row.values)
print(first_row.keys())
#keys는 속성이 아니라 method
#이때 keys는 index와 같은 역할을 하는 method이므로 출력값이 같아짐

#시리즈의 기초 통계 method 이용하기
ages=scientists['Age']
print(ages)
#시리즈를 구성하는 데이터가 정수일 경우 통계 method 이용가능
print(ages.mean())
print(ages.min())

#3.시리즈 다루기-응용
scientists=pd.read_csv('drive/MyDrive/scientists.csv')
ages=scientists['Age']
print(ages)
print(ages.max())
print(ages.mean())
#평균 나이보다 나이가 많은 사람의 데이터를 추출
print(ages[ages>ages.mean()])#조건식을 만족한 값만 출력

#시리즈와 브로드 캐스팅
#브로드캐스팅: 모든 데이터에 대해 한 번에 연산하는 것
print(ages+ages) #벡터와 벡터
print(ages+100) #벡터와 스칼라

#4. 데이터프레임 다루기
#데이터프레임의 age 열에서 age 열의 평균보다 높은 행만 출력
print(scientists[scientists['Age']>scientists['Age'].mean()])

#5. 시리즈와 데이터프레임의 데이터 처리하기
print(type(scientists[['Born','Died']]))

"""#3. 그래프 그리기"""

import seaborn as sns
import matplotlib.pyplot as plt

#1.데이터 시각화가 필요한 이유
ancombe=sns.load_dataset('anscombe')
print(ancombe) #4개의 데이터셋으로 이루어져 있음

import

dataset1=ancombe[ancombe['dataset']=='I'] #불러온 데이터에서 데이터셋이 1인 그룹만 dataset1로 다시 지정
#어떤 컬럼이 x축,y축에 들어갈 것인지 직접 지정
plt.plot(dataset1['x'],dataset1['y']) #plot은 기본적으로 선을 통해 그래프를 그림
plt.plot(dataset1['x'],dataset1['y'],'o') #특정 문자로 지정하고싶은 경우

#한번에 4개의 그래프 그리기
#step1. 각 그룹별로 지정해주기
dataset2=ancombe[ancombe['dataset']=='II']
dataset3=ancombe[ancombe['dataset']=='III']
dataset4=ancombe[ancombe['dataset']=='IV']
#step2. 그래프 격자가 위치할 기본 틀 만들기
fig=plt.figure()
#step3 add_subplot method으로 그래프 격자를 그리기
axes1=fig.add_subplot(2,2,1)
axes2=fig.add_subplot(2,2,2)
axes3=fig.add_subplot(2,2,3)
axes4=fig.add_subplot(2,2,4)
#step4. plot method에 데이터를 전달하여 그래프 그리기
axes1.plot(dataset1['x'],dataset1['y'],'o')
axes2.plot(dataset2['x'],dataset2['y'],'o')
axes3.plot(dataset3['x'],dataset3['y'],'o')
axes4.plot(dataset4['x'],dataset4['y'],'o')
#step4. 데이터 이름 지정해주기
axes1.set_title("dataset1")
axes2.set_title("dataset2")
axes3.set_title("dataset3")
axes4.set_title("dataset4")
fig.suptitle("Anscombe's data")

"""의미: 평균, 분산, 상관관계, 회귀선의 통계 수치가 같아도 그래프의 형태는 다를 수 있음

즉, 데이터 분석 시 수치에만 의존하면 잘못된 판단을 할 수 있다는 것을 알려줌
"""

#2, matplotlib 라이브러리 자유자재로 사용하기
#matplotlib에 존재하는 다양한 메서드 활용하기
#고급 그래프 라이브러리인 seaborn 이용하기

tips=sns.load_dataset("tips")
print(tips.head())
print(type(tips))

#히스토그램 그리기 (일변량 그래프)
#하나의 열만 사용하는 것을 일변량 그래프라고 함
fig=plt.figure()
axes1=fig.add_subplot(1,1,1)
#기본 틀을 마련하고 그래프 격자를 구성함
axes1.hist(tips['total_bill'],bins=10) #x축 간격은 bins인자값을 조정
axes1.set_title("Histogram of Total Bill") #전체 그래프 제목
axes1.set_xlabel("Frequency") #x축 name
axes1.set_ylabel("Total Bill") #y축 name

#산점도 그래프 그리기 #이분산성 파악 #이변량 그래프
fig=plt.figure()
axes1=fig.add_subplot(1,1,1)
axes1.scatter(tips['total_bill'],tips['tip'])
axes1.set_title("Scatter Plot of Total Bill vs Tip")
axes1.set_xlabel("Total Bill")
axes1.set_ylabel("Tip")

# 상자그림 그리기 #이상점 파악 #이변량 그래프
boxplot=plt.figure()
axes1=boxplot.add_subplot(1,1,1)
axes1.boxplot([tips[tips['sex']=='Female']['tip'],tips[tips['sex']=='Male']['tip']],labels=['Female','Male'])
axes1.set_xlabel('Sex')
axes1.set_ylabel('Tip')
axes1.set_title('Boxplot of Tips by Sex')

#3. seaborn라이브러리 자유자재로 사용하기
#히스토그램-subplots,distplot
#산점도- regplot
#히스토그램과 산점도 동시에 jointplot
#박스그래프-boxplot
#관계그래프 pairplot

#히스토그램
ax = sns.displot(tips['total_bill'])
ax.fig.suptitle("Total Bill Histogram with Density Plot") # Set the title on the figure
ax.set_axis_labels("Total Bill", "Frequency") # Set axis labels

#카운트 그래프
ax=plt.subplots()
ax=sns.countplot(tips['day'])
ax.set_title('Count of days')
ax.set_xlabel('Day of the Week')
ax.set_ylabel('Frequency')

"""#4.데이터 연결하기"""

#분석하기 좋은 데이터 집합을 만들기 위해 여러 개의 데이터 집합을 연결하거나 추출하여 데이터를 정리하는 방법

import pandas as pd

#1. 분석하기 좋은 데이터
#분석하기 좋은 데이터란 데이터 집합을 분석하기 좋은 상태로 만들어 놓은 것

#2. 데이터 연결 기초
df1=pd.read_csv('drive/MyDrive/concat_1.csv')
df2=pd.read_csv('drive/MyDrive/concat_2.csv')
df3=pd.read_csv('drive/MyDrive/concat_3.csv')
#concat method는 데이터 프레임을 연결할 떄 위에서 아래 방향으로 연결
#concat으로 데이터 프레임을 연결할 경우 열이름과 인덱스가 그대로 유지됨
row_concat=pd.concat([df1,df2,df3]) #3개의 데이터 프레임을 리스트처럼 연결
print(row_concat) #열 이름 (A,B,C,D) 유지, 인덱스 번호 (0,1,2,3) 유지
print(row_concat.iloc[3,]) #4번째 행 추출

#데이터 프레임에 시리즈 연결하기
new_row_series=pd.Series(['n1','n2','n3','n4']) #시리즈 형성
print(pd.concat([df1,new_row_series])) #데이터프레임과 시리즈 연결
#결과를 보면 시리즈가 하나의 행으로 추가되는 것이 아닌, 열로 추가된다!
#이유: 시리즈에는 열 이름이 없기 때문에 각각의 열에 맞는 행으로 추가되는 것이 아닌, 새로운 열로 추가

#행 1개로 구성된 데이터프레임 생성하여 연결하기
new_row_df=pd.DataFrame([['n1','n2','n3','n4']],columns=['A','B','C','D']) #판다스에서 데이터프레임 형성 문법 확인
print(new_row_df)
print(pd.concat([df1,new_row_df]))
#concat은 2개 이상의 데이터프레임을 연결할 때 사용하는 method
#1개의 데이터 프레임을 연결할때는 append 이용

#다양한 방법으로 데이터 연결하기
row_concat_i=pd.concat([df1,df2,df3],ignore_index=True) #이 경우 데이터를 연결한 다음 인덱스를 0부터 다시 지정
print(row_concat_i)
col_concat=pd.concat([df1,df2,df3],axis=1) #데이터프레임을 세로로 연결하고 싶을 때
print(col_concat)
print(col_concat['A']) #데이터 프레임에서 열 이름으로 추출할 경우 해당 이름을 가진 모든 열을 추출한다
col_concat['new_col']=['n1','n2','n3','n4'] #새로운 열 추가
print(col_concat)
col_concat=pd.concat([df1,df2,df3],axis=1,ignore_index=True)
print(col_concat)

#공통 열과 공통 인덱스만 연결하기
df1.columns=['A','B','C','D'] #앞에서 사용한 데이터 프레임 열 이름 다시 지정
df2.columns=['E','F','G','H']
df3.columns=['A','C','F','H']
print(df1)
print(type(df1)) #데이터 프레임
print(df2)
print(type(df2))
print(df3)
print(type(df3))
row_concat=pd.concat([df1,df2,df3])
print(row_concat) #누락값 등장
#이런 누락값 없이 데이터프레임을 연결하는 방법-> 공통된 열만 골라서 연결
print(pd.concat([df1,df2,df3],join='inner')) #3개의 데이터프레임의 공통된 열은 없기 때문에 empty출력
print(pd.concat([df1,df3],ignore_index=True,join='inner'))

#데이터를 행 방향으로 연결
df1.index=[0,1,2,3] #인덱스 직접 지정
df2.index=[4,5,6,7]
df3.index=[0,2,5,7]
print(df1)
print(df2)
print(df3)
#concat method로 데이터프레임을 행방향 연결
print(pd.concat([df1,df2,df3],axis=1))
#누락값 없이 연결하는 방법-> 공통된 행만 출력
print(pd.concat([df1,df3],axis=1,join='inner'))

#3. 데이터 연결 마무리
person=pd.read_csv('drive/MyDrive/survey_person.csv')
site=pd.read_csv('drive/MyDrive/survey_site.csv')
survey=pd.read_csv('drive/MyDrive/survey_survey.csv')
visited=pd.read_csv('drive/MyDrive/survey_visited.csv')

print(person)
print(site)
print(survey)
print(visited)
visited=visited.loc[[0,2,6],]
print(visited)

#merge를 이용하여 site와 visited 합치기
merged1=site.merge(visited,left_on='name',right_on='site')
print(merged1)
#person과 survey 합치기
merged2=person.merge(survey,left_on='ident',right_on='person')
print(merged2)

"""#5. 누락값 처리하기"""

import numpy as np
np.nan
#누락값의 의미
#누락값은 0아니고 공백도 아니라는 것에 유의
print(np.nan==True)
print(np.nan==False)
print(np.nan=='')
print(np.nan==0)
#누락값을 확인하는 방법-> isnull(판다스 내장)
print(pd.isnull(np.nan))

#누락값이 생기는 이유
#1) 누락값이 있는 데이터 집합을 연결할 때 누락값이 생기는 경우
visited=pd.read_csv('drive/MyDrive/survey_visited.csv')
survey=pd.read_csv('drive/MyDrive/survey_survey.csv')
print(visited) #visited 데이터는 6행에 누락값이 존재
print(survey) #visited 데이터는 9행, 10행에 누락값이 존재

#만약 이렇게 누락값이 존재하는 상태에서 merge를 이용해 병합한다면?
vs=visited.merge(survey,left_on='ident',right_on='taken')
print(vs) #누락값이 더 많이 생겨남을 알 수 있음

#2) 데이터를 입력할 때 누락값이 생기는 경우
#-> 애초에 nan으로 입력이 되는 경우

#3) 범위를 지정하여 데이터를 추출할 떄 누락값이 생기는 경우
gapminder=pd.read_csv("drive/MyDrive/gapminder.tsv",sep='\t')
df=gapminder.groupby('year')['lifeExp'].mean()
print(df)
#여기서 range method를 이용해 2000~2009년의 데이터 추출하기
print(df.loc[range(2000,2010),]) #오류발생
#이 오류를 해결하기 위해서는 조건식을 이용!

#누락값의 개수
ebola=pd.read_csv("drive/MyDrive/country_timeseries.csv")
#누락값이 아닌 값의 개수
print(ebola.count()) #각 컬럼별로 누락값이 아닌 값의 개수를 반환
#count를 이용해서 누락값의 개수를 세는 방법
#count_nonzero, isnull 이용
print(np.count_nonzero(ebola.isnull()))
print(np.count_nonzero(ebola['Cases_Guinea'].isnull())) #특정열에서 누락값인 것

#누락값 처리하기-변경, 삭제
#1) 누락값 변경하기-fillna()
#처리해야 하는 데이터프레임의 크기가매우 크고 메모리를 효율적으로 사용해야 하는 경우에 자주 사용
print(ebola.fillna(0).iloc[0:10,0:5]) #누락값을 0으로 처리
print(ebola.fillna(method='ffill').iloc[0:10,0:5]) #다시 누락값으로 변경
print(ebola.fillna(method='bfill').iloc[0:10,0:5])
#누적값 양쪽에 있는 값을 이용하여 중간값을 구한 다음 누락값을 처리 interpolate()
print(ebola.interpolate().iloc[0:10,0:5])
#2) 누락값 삭제하기-dropna
ebola_dropna=ebola.dropna()
print(ebola_dropna)

#누락값이 포함된 데이터 계산하기

#1) 단순 사칙연산의 경우 누락값이 하나라도 존재한다면, 그 계산결과는 누락값이 된다
ebola['Case_multiple']=ebola['Cases_Guinea']+ebola['Cases_Liberia']+ebola['Cases_SierraLeone']
df=ebola.loc[:,['Cases_Guinea','Cases_Liberia','Cases_SierraLeone','Case_multiple']]
print(df.head(n=10))
#2) 계산함수를 이용할경우 누적값을 제외하고 계산하기 가능
print(ebola.Cases_Guinea.sum(skipna=True))
print(ebola.Cases_Guinea.sum(skipna=False))

"""#6. 깔끔한 데이터"""

#1. 열과 피벗
#melt method 지정한 열의 데이터를 모두 행으로 정리

import pandas as pd
#1) 1개의 열만 고정하고 나머지 열을 행으로 바꾸기

pew=pd.read_csv("drive/MyDrive/pew.csv") #미국의 소득과 종교데이터 원래는 11개의 열
print(pew.head())
print(pew.iloc[:,0:6]) #6개의 열만 출력

pew_long=pd.melt(pew,id_vars='religion') #종교를 고정하고 나머지는 각각의 종교에 맞는 행으로 정리됨
print(pew_long.head()) #지금 이 상태를 religion 열을 고정하여 피벗했다라고 말함
pew_long=pd.melt(pew,id_vars='religion', var_name='income', value_name='count') #열 이름을 바꾸는 방법
print(pew_long.head())

#2) 두개 이상의 열을 고정하고 나머지 열을 행으로 바꾸기
billboard=pd.read_csv("drive/MyDrive/billboard.csv")
print(billboard.iloc[0:5,0:16])
#여기서 year. artist, time, date.entered 열을 모두 고정하고 나머지 열을 피벗
bilboard_long=pd.melt(billboard,id_vars=['year','artist','track', 'time','date.entered'],var_name='week',value_name='rating')
print(bilboard_long.head())

#2. 열 이름 관리하기

#1) 하나의 열이 여러 의미를 가지고 있는 경우 '
ebola=pd.read_csv("drive/MyDrive/country_timeseries.csv")
print(ebola.columns) #이중에서 death_guniea는 사망자 수와 나라이름을 합쳐 만든 이름
#이처럼 하나의 열이 여러가지 의미를 가지고 있다는 것이 무엇인지 알아보기
print(ebola.iloc[:5,[0,1,2,3,10,11]])
#date와 day를 고정하고 나머지를 행으로 피벗-> 나라별 사망자 수를 행으로 확인
ebola_long=pd.melt(ebola,id_vars=['Date','Day'])
print(ebola_long.head())
#case_guinea와 같이 2개 이상의 의미를 가지고 있는 열 이름을 밑줄을 기준으로 분리 가능

#열 이름 분리하고 데이터프레임에 추가하기
variable_split=ebola_long.variable.str.split('_') #자료형은 시리즈, 각각의 시리즈에 저장된 값은 리스트
print(variable_split[:5]) #전자는 발병과 죽음과 같은 상태를 의미하고, 후자는 나라 이름을 의미
print(type(variable_split))

status_values=variable_split.str.get(0)
country_values=variable_split.str.get(1)
print(status_values[:5])
print(status_values[-5:])
print(country_values[:5])
print(country_values[-5:])

ebola_long['status']=status_values
ebola_long['country']=country_values
print(ebola_long.head())

#3. 여러 열을 하나로 정리하기
weather=pd.read_csv('drive/MyDrive/weather.csv')
print(weather.iloc[:5,:])

#날짜 열을 행 데이터로 피벗
weather_long=pd.melt(weather,id_vars=['id','year','month','element'],var_name='day',value_name='temp')
print(weather_long.head())

#4.중복 데이터 처리하기

bilboard=pd.read_csv('drive/MyDrive/billboard.csv')
bilboard_long=pd.melt(bilboard,id_vars=['year','artist','track','time','date.entered'],var_name='week',value_name='rating')
print(bilboard_long.head())

#노래제목이 loser인 행 데이터만 추출해보면, 중복 데이터가 꽤 많은 것을 알 수 있다
print(bilboard_long[bilboard_long.track=='Loser'].head())

#중복된 값을 가진 열을 따로 리스트로 저장
bilboard_songs=bilboard_long[['year','artist','track','time']]
print(bilboard_songs.shape)

#중복 데이터 제거
bilboard_songs=bilboard_songs.drop_duplicates()
print(bilboard_songs.shape)

"""#7. 판다스 자료형"""

#1. 자료형 다루기
import pandas as pd
import seaborn as sns

tips=sns.load_dataset("tips") #seaborn 라이브러리에서 데이터셋 불러오기
tips.head()

#자료형 변환- astype
#sex열의 데이터를 문자열로 변환하여 sex_tr이라는 새로운 열에 저장
tips['sex_tr']=tips['sex'].astype(str)
print(tips.dtypes) #판다스에서 문자열은 object로 표현

#자료형이 변환된 데이터 다시 원래대로 만들기
tips['total_bill']=tips['total_bill'].astype(str) #total_bill의 타입을 문자열로 바꿈
print(tips.dtypes)
tips['total_bill']=tips['total_bill'].astype(float) #total_bill의 타입을 실수로 바꿈
print(tips.dtypes)

#잘못 입력한 데이터 처리하기

#1) total_bill 열의 1,3,5,7행의 데이터를 'missing'으로 바꿔 변수 tips_sub_miss에 저장
tips_sub_miss=tips.head(10)
tips_sub_miss.loc[[1,3,5,7],'total_bill']='missing'
print(tips_sub_miss)
print(tips_sub_miss.dtypes) #total_bill의 자료형이 실수가 아니라 문자형

#이때 astype을 이용해 문자열-> 실수 변환시 오류 발생
#판다스는 missing이라는 문자열을 실수로 변환하는 방법을 모르기 때문에

tips_sub_miss['total_bill']=pd.to_numeric(tips_sub_miss['total_bill'],errors='ignore')
print(tips_sub_miss.dtypes) #여전히 타입은 문자열
tips_sub_miss['total_bill']=pd.to_numeric(tips_sub_miss['total_bill'],errors='coerce') #이경우 missing이라는 문자열 값이 nan으로 바뀜
print(tips_sub_miss.dtypes)

#2) 카테고리 자료형

#tips에서 sex컬럼은 원래 남자 또는 여자만으로 구성되어있어 카테고리 자료형으로 저장
tips['sex']=tips['sex'].astype('str') #카테고리-> 문자열
print(tips.info()) #저장용량=10.8+KB
tips['sex']=tips['sex'].astype('category') #문자열-> 카테고리
print(tips.info()) #저장용량=9.3+KB
#의미-> 반복되는 문자열로 구성된 데이터는 카테고리를 사용하는 것이 더 효율적임

"""#8. 문자열 처리하기"""

#1. 문자열 다루기
word='grail'
sent='a scatch'

#각 문자열의 첫 번째 문자 추출
print(word[0])
print(sent[0])
#인덱스 슬라이싱을 이용해서 여러 개의 문자를 한 번에 추출
print(word[0:3])
#음수를 사용하여 문자열 추출
print(sent[-1])
print(sent[0:-3])

#전체문자열 추출하기
#왼쪽 범위가 비어있음-> 문자열의 첫 번째 위치부터 문자열을 추출
#오른쪽 범위가 비어있음-> 문자열의 마지막 위치까지 문자열을 추출

print(word[:])
print(sent[:])

#문자열을 일정한 간격으로 건너뛰며 추출
print(word[::2]) #2칸씩 건너뛰며 추출
print(sent[::3]) #3칸씩 건너뛰며 추출

#2.문자열 메서드
#문자열이 너무 길어서 내가 원하는 문자가 몇 번째 인덱스에 있는지 파악하기 어려울때
#문자열에 포함된 소문자를 모두대문자로 바꾸고 싶을때

#join 메서드
#문자열을 연결하여 새로운 문자열을 반환하는 메서드
d1='40도'
m1="'46'"
s1='52.837'
u1='N'

d2='73도'
m2="'58'"
s2='26.302'
u2='W'

coords=''.join([d1,m1,s1,u1,d2,m2,s2,u2])
print(coords)

#splitliness
#여러 행을 가진 문자열을 분리한 다음 리스트로 반환

"""#9. apply 매서드 활용


"""

#apply-> 사용자가 작성한 함수를 한 번에 데이터프레임의 각 행과 열에 적용하여 실행할 수 있게 해주는 메서드
#대용량 데이터에 함수를 브로드캐스팅 하는 경우 사용

#1. 간단한 함수 만들기 (사용자 정의 함수)

def my_sq(x):
  return x**2 #제곱함수 만들기

def my_exp(x,n):
  return x**n  #n제곱함수 만들기

print(my_sq(2))
print(my_exp(2,4))

#2. apply 메서드 사용하기-기초

#시리즈와 데이터프레임에 apply 메서드 사용하기

import pandas as pd
df=pd.DataFrame({'a':[10,20,30],'b':[20,30,40]})
print(df)

#a열 제곱
print(df['a']**2)
#apply 메서드에 제곱 함수의 이름을 전달하여 시리즈이 모든 데이터에 제곱 함수를 적용한 것
sq=df['a'].apply(my_sq) #a열에 apply 함수를 이용하여 브로드캐스팅
print(sq)

#데이터프레임과 apply 메서드
df=pd.DataFrame({'a':[10,20,30],'b':[20,30,40]}) #데이터프레임 형성
print(df)

def print_me(x): #새로운 함수 형성
  print(x)

#데이터프레임에 함수를 적용할 때는 열방향으로 적용할 것인지, 행방향으로 적용할 것인지 결정
#axis=0이면 열 axis=1이면 행

print(df.apply(print_me,axis=0))

#3개의 인자를 입력받아 평균을 계산하는 함수 사용

def avg_3(x,y,z):
  return (x+y+z)/3

print(avg_3(1,2,3))

#이때 print(df.apply(avg_3))를 진행할 경우, df에서 각각의 열을 입력받아
#3개의 인자를 입력해야한다는 오류가 발생한다.
#따라서 apply가 열 단위로 데이터를 처리할 수 있도록

def avg_3_apply(col):
  x=col[0]
  y=col[1]
  z=col[2]
  return (x+y+z)/3

print(df.apply(avg_3_apply)) #열 단위로 평균을 계산해줌

#3. apply 메서드 사용하기-고급
import seaborn as sns
titanic=sns.load_dataset('titanic')
print(titanic.info())

#누락값의 개수를 반환하는 count_missing함수 만들기
import numpy as np
def count_missing(vec):
 null_vec=pd.isnull(vec)
 null_count=np.sum(null_vec)
 return null_count

cmis_col=titanic.apply(count_missing)
print(cmis_col)

#누락값의 비율을 계산하는 prop_missing 함수 만들기

def prop_missing(vec):
  num=count_missing(vec)
  dem=vec.size
  return num/dem

pmis_col=titanic.apply(prop_missing)
print(pmis_col)

#누락값이 아닌 데이터의 비율을 구하는 prop_complete 함수 만들기

def prop_complete(vec):
  return 1-prop_missing(vec)

pcom_col=titanic.apply(prop_complete)
print(pcom_col)

from pdb import pm
#데이터 프레임의 누락값 처리하기-행방향
cmis_row=titanic.apply(count_missing,axis=1)
pmis_row=titanic.apply(prop_missing,axis=1)
pcom_row=titanic.apply(prop_complete,axis=1)
print(cmis_row.head())
print(pmis_row.head())
print(pcom_row.head())

#행별로 누락값의 개수를 구하여 num_missing이라는 새로운 컬럼으로 추가하기
titanic['num_missing']=titanic.apply(count_missing,axis=1)
print(titanic.head())

#누락값이 2개 이상인 데이터를 추출
print(titanic.loc[titanic.num_missing>1,:].sample(10))

"""#10. 그룹연산"""

#데이터를 분할, 반영, 결합하는 과정

#1. 데이터 집계

import pandas as pd
df=pd.read_csv('drive/MyDrive/gapminder.tsv',sep='\t')

print(df.head())

#year을 기준으로 데이터를 그룹화한 다음 lifeExp열의 평균을 구하기

avg_life_exp_by_year=df.groupby('year')['lifeExp'].mean()
print(avg_life_exp_by_year)

#분할-반영-결합 과정 살펴보기

#groupby에 life를 전달하면 가장 먼저 연도별로 데이터를 나누는 과정이 진행됨
years=df.year.unique() #분할
print(years)

#연도별로 평균값을 구함
#연도별 데이터 추출-> 평균값 계산 # 반영
y1952=df.loc[df.year==1952, :] #1952년 데이터만 추출
print(y1952.head())
y1952_mean=y1952.lifeExp.mean() #1952년 평균값 계산
print(y1952_mean)

#위 과정을 연도별로 수행한뒤 결합한 것이 groupby의 결과와 같다고 할 수 있음

#평균값을 구하는 사용자 함수와 groupby메서드
def my_mean(values):
  n=len(values)
  sum=0
  for value in values:
    sum+=value
  return sum/n

#2개의 인잣값을 받아 처리하는 사용자 함수와 groupby메서드

def my_mean_diff(values,diff_value):
  n=len(values)
  sum=0
  for value in values:
    sum+=value
  mean=sum/n
  return mean-diff_value

#여러개의 집계 메서드 한 번에 사용하기-agg메서드 이용

import numpy as np
gdf=df.groupby('year').lifeExp.agg([np.count_nonzero,np.mean,np.std])
print(gdf)

#집계 메서드를 딕셔너리에 담아 agg메서드에 전달
#키로 집계 메서드를 적용할 열 이름을 전달하고, 딕셔너리의 값으로 집계 메서드를 전달

gdf_dict=df.groupby('year').agg({'lifeExp':'mean','pop':'median','gdpPercap':'median'})
print(gdf_dict)

#2. 데이터 변환

#1) 표준점수 계산하기

def my_zscores(x):
  return(x-x.mean())/x.std() #표준화 값

#각 연도별 lifeExp 열의 표준점수 계산
#my_zscores를 적용하기 위해 transform메서드 사용

z=df.groupby('year')['lifeExp'].transform(my_zscores)
print(z.head())

#2) 누락값을 평균값으로 처리하기

import seaborn as sns
import numpy as np

np.random.seed(42)
tips10=sns.load_dataset('tips').sample(10) #10개의 행 데이터만 가져옴
tips10.loc[np.random.permutation(tips10.index)[:4],'total_bill']=np.nan
#total_bill 열의 값 4개를 임의로 선택하여 누락값 nan으로 바꿈
print(tips10)

#단순히 누락값을 전체 평균으로 채우면 안되는 이유는 현재 tips10데이터는 여성보다 남성의 데이터가 많기 때문에
#전체 평균을 적용할 경우 여성 데이터가 훼손됨

count_sex=tips10.groupby('sex').count()
print(count_sex)
#남성의 누락값은 3개, 여성의 누락값은 1개

#성별을 구분하여 total_bill의 값을 받아 평균값을 구하는 사용자 정의 함수

def fill_na_mean(x):
  avg=x.mean()
  return x.fillna(avg)

total_bill_group_mean=tips10.groupby('sex').total_bill.transform(fill_na_mean)
tips10['fill_total_bill']=total_bill_group_mean
print(tips10)

#3. 데이터 필터링

tips=sns.load_dataset('tips')
print(tips.shape)
print(tips.head())
#size열의 데이터 수를 확인
print(tips['size'].value_counts())
#1,5,6 테이블의주문이 매우 적음

#30번 이상의 주문이있는 테이블만 추려서?
tips_filtered=tips.groupby('size').filter(lambda x:x['size'].count()>=30)
print(tips_filtered.shape)
print(tips_filtered['size'].value_counts())

#4. 그룹 오브젝트

#1) 그룹 오브젝트 저장하여 살펴보기

#tips데이터 집합에서 임의로 10개의 데이터를 추출

tips_10=sns.load_dataset('tips').sample(10,random_state=42)
print(tips_10)

#sex로 그룹화
grouped=tips10.groupby('sex')
print(grouped) #지료형이 그룹 오브젝트
print(grouped.groups)

#2) 그룹 오브젝트의 평균 구하기
avgs=grouped[['total_bill','tip','size']].mean()
print(avgs)

#3) 그룹 오브젝트에서 데이터 추출하고 반복하기-get_group 이용
female=grouped.get_group('Female')
print(female)

#4) 그룹 오브젝트 계산하고 살펴보기
bill_sex_time=tips.groupby(['sex','time'])
group_avg=bill_sex_time[['total_bill','tip','size']].mean()
print(group_avg)

print(type(group_avg))
print(group_avg.columns)
print(group_avg.index)

"""#12. 시계열 데이터"""

#1. datatime 오브젝트

from datetime import datetime

#now,today 메서드-> 현재 시간 출
now1=datetime.now() #
print(now1)

now2=datetime.today()
print(now2)

#datetime 오브젝트를 생성할 때 시간을 직접 입력
t1=datetime.now()
t2=datetime(1970,1,1) #시간입력 안하면 자정으로 설정
t3=datetime(1970,12,12,13,24,34)
print(t1,t2,t3)

#시간 계산 가능

diff1=t1-t2
print(diff1)
print(type(diff1))

diff2=t2-t1
print(diff2)
print(type(diff2))

#문자열을 datetime 오브젝트로 변환하기

import pandas as pd
import os

ebola=pd.read_csv('drive/MyDrive/country_timeseries.csv')
print(ebola.info()) #date컬럼의 자료형이 문자형임
#이를 datetime오브젝트로 변환하기

ebola['date_dt']=pd.to_datetime(ebola['Date'])
print(ebola.info())

#날짜 형식 포맷팅

test_df1=pd.DataFrame({'order_day':['01/01/15','02/01/15','03/01/15']})
#시간형식 지정자 이용

test_df1['date_dt1']=pd.to_datetime(test_df1['order_day'],format='%d/%m/%y')
test_df1['date_dt2']=pd.to_datetime(test_df1['order_day'],format='%m/%d/%y')
test_df1['date_dt3']=pd.to_datetime(test_df1['order_day'],format='%y/%m/%d')
print(test_df1)

#datetime 오브젝트로 변환할는 열을 지정하여 데이터 집합 불러오기

#데이터를 불러올 때부터 date컬럼의 자료형을 datetime으로 불러오는 방법

ebola1=pd.read_csv('drive/MyDrive/country_timeseries.csv',parse_dates=['Date'])
print(ebola1.info()) #datetime으로 불러와짐

#datetime 오브젝트에서 날짜 정보 추출하기

date_series=pd.Series(['2018-05-16','2018-05-17','2018-05-18'])
d1=pd.to_datetime(date_series) #문자열로 저장된 날짜를 시리즈에 담아 데이트타임으로 변환
print(d1)

print(d1[0].year)
print(d1[0].month)
print(d1[0].day)

#dt접근자로 시게열 데이터 정리하기

ebola=pd.read_csv('drive/MyDrive/country_timeseries.csv')
ebola['date_dt']=pd.to_datetime(ebola['Date'])

#dt 접근자를 사용하지 않고 인덱스가 3인 데이터의 년, 월, 일 데이터를 추출

print(ebola[['Date','date_dt']].head())

print(ebola['date_dt'][3].year)
print(ebola['date_dt'][3].month)
print(ebola['date_dt'][3].day)

#2. 사례별 시계열 데이터 계산하기

#1) 에볼라 최초 발병일 계산하기

print(ebola.iloc[-5:,:5]) #마지막 행과 열을 5개
#데이터가 시간 역수으로 정렬

print(ebola['date_dt'].min()) #min메서드를 이용하여 최초 발병일을 찾음
print(type(ebola['date_dt'].min()))

#에볼라의 진행 정도

ebola['outbreak_d']=ebola['date_dt']-ebola['date_dt'].min()
print(ebola['outbreak_d'])

#2) 파산한 은행의 개수 계산하기

banks=pd.read_csv('drive/MyDrive/banklist.csv')
print(banks.head())
print(banks.info())
#closing date와 updated date 열은 모두 문자형
#이를 read_csv의 parse_dates를 이용해 datetime오브젝트로 변경

banks=pd.read_csv('drive/MyDrive/banklist.csv',parse_dates=[5,6])
print(banks.info())

#dt 접근자와 quater속성을 이용하면 은행이 파산한 연도, 분기를 알 수 있음
banks['closing_quarter'],banks['closing_year']=(banks['Closing Date'].dt.quarter,banks['Closing Date'].dt.year)
print(banks.head())

#groupby를 이용해 연도별로 파산한 은행이 얼마나 되는지 확인
closing_year=banks.groupby(['closing_year']).size()
print(closing_year)

#연도별, 분기별
closing_year_quarter=banks.groupby(['closing_year','closing_quarter']).size()
print(closing_year_quarter)